version: '3'

services:
  endlist-web:
    build: ./endlist-web
    image: endlist_web
    stdin_open: true
    ports:
      - 80:80
    links:
      - endlist-db
    volumes:
      - ./endlist-web/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ../../frontend/dist:/var/www/html
      - ../../backend:/var/www/html/backend
    networks:
      - default

  endlist-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ../../backend/db:/var/lib/mysql
