language: node_js
  node_js:
    - "6.9.4"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - frontend/node_modules
    - backend/vendor

matrix:
  include:
    - language: php
      php: 7.0
      before_script:
        - cd backend
      script:
        - composer install
      afer_script:
        - cd ../

script:
  - grunt
