language: node_js
node_js:
  - "6.9.4"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - frontend/node_modules
    - backend/vendor


before_script:
  - npm run install

script:
  - npm run test
